name = "poe-proxy"
compatibility_date = "2023-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
main = "src/worker.js"

[build]
command = "docker build -t poe-proxy ."

[vars]
WORKERS_RS_VERSION = "0.0.11"

[[services]]
binding = "POE_SERVICE"
type = "table"
format = "postgres"

[[services.ports]]
port = 8080
external = true

[env.production]
routes = [
  { pattern = "api.your-domain.com/*", zone_name = "your-domain.com" }
]

[triggers]
crons = ["*/5 * * * *"]